### ISSUE TITLE
在调用 Db.CodeFirst.InitTables(@"xxx.xxx.models");  显示System.IO.FileNotFoundException: Could not load file or assembly

### ISSUE THREAD

**Issue by PSC-F** [DotNetNext/SqlSugar#1237]
> [!WARNING]
> 在Aspire 中引入 SqlSugar 初始化数据库表结构，调用按指定命名空间初始化表时找不到程序集
### 
* 使用版本
```ruby
<PackageReference Include="SqlSugarCore" Version="5.1.4.152" />
```
* 堆栈
``` ruby
An unhandled exception has occurred while executing the request.
      System.IO.FileNotFoundException: Could not load file or assembly 'ZhangPengFei.IoT.ApiService.Model, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
      File name: 'ZhangPengFei.IoT.ApiService.Model, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
         at System.Reflection.Assembly.Load(String assemblyString)
         at SqlSugar.CodeFirstProvider.InitTables(String entitiesNamespace)
         at ZhangPengFei.IoT.ApiService.DataBase.DataBaseManager.BuildWithMySQL() in C:\Users\doudo\RiderProjects\Aspire.IoT\AspireIoT\ZhangPengFei.IoT.ApiService\DataBase\DataBaseManager.cs:line 40
         at ZhangPengFei.IoT.ApiService.EndPoints.GateWayEndPoints.Services.GateWayService..ctor(MySqlDataSource dataSource) in C:\Users\doudo\RiderProjects\Aspire.IoT\AspireIoT\ZhangPengFei.IoT.ApiService\EndPoints\GateWayEndPoints\Services\GateWayService.cs:line 11
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
         at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at lambda_method4(Closure, Object, HttpContext)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.Invoke(HttpContext context)
``` 

* 临时解决方案
```ruby
Db.DbMaintenance.CreateDatabase();
        // todo: bug System.IO.FileNotFoundException: Could not load file or assembly
        // Db.CodeFirst.InitTables(@"ZhangPengFei.IoT.ApiService.Model");
        // todo: fix init tables
        Assembly assembly = Assembly.GetExecutingAssembly();
        var types = assembly.GetTypes().Where(t => t.Namespace == typeof(GateWay).Namespace).ToArray();
        Db.CodeFirst.InitTables(types);
    
```

**Comment by DotNetNext** [comment]
不要用这个方法，建议用这种
![image](https://github.com/DotNetNext/SqlSugar/assets/12455385/4b32b2e9-abb8-414b-b4bb-9faac932b9ac)

**Comment by DotNetNext** [comment]
![image](https://github.com/DotNetNext/SqlSugar/assets/12455385/0afa760a-0885-44ac-a656-cad8fc503b66)
string重载只是用的微软底层方法，可能不能跨程序集。

**Comment by PSC-F** [comment]
> ![image](https://private-user-images.githubusercontent.com/12455385/325519928-0afa760a-0885-44ac-a656-cad8fc503b66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzE3MDgsIm5iZiI6MTcxNDAzMTQwOCwicGF0aCI6Ii8xMjQ1NTM4NS8zMjU1MTk5MjgtMGFmYTc2MGEtMDg4NS00NGFjLWE2NTYtY2FkOGZjNTAzYjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA3NTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZTNkYzRhYzllNDNhYWZhZjU1NGQ2NzQxYTlhYjEzZTEwMjU5ZDc0NGIzODFlMzI5YjJjMDBjMjA0ZjQzMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-NunWYqP0fn-Us4dygqcAwc2JijwcsxFvN5abl1IUSg) string重载只是用的微软底层方法，可能不能跨程序集。

好的，知道了感谢 👍
