### ISSUE TITLE
CopyNew要怎麼Mock？

### ISSUE THREAD

**Issue by flier268** [DotNetNext/SqlSugar#1290]
SqlSugarClient似乎有非常複雜的建構子
CopyNew偏偏又是回傳class，而不是interface
```C#

    private Mock<ISqlSugarClient> _mockDb;
    [SetUp]
    public void Setup()
    {
        _mockDb = new Mock<ISqlSugarClient>();
         _mockDb.Setup(client => client.CopyNew()).Returns(new Mock<SqlSugarClient>().Object);
    }

```

System.ArgumentException : Can not instantiate proxy of class: SqlSugar.SqlSugarClient.
Could not find a parameterless constructor. (Parameter 'constructorArguments')
  ----> System.MissingMethodException : Constructor on type 'Castle.Proxies.SqlSugarClientProxy' not found.
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyInstance(Type proxyType, List`1 proxyArguments, Type classToProxy, Object[] constructorArguments)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
   at Moq.CastleProxyFactory.CreateProxy(Type mockType, IInterceptor interceptor, Type[] interfaces, Object[] arguments) in /_/src/Moq/Interception/CastleProxyFactory.cs:line 62
   at Moq.Mock`1.InitializeInstance() in /_/src/Moq/Mock`1.cs:line 309
   at Moq.Mock`1.OnGetObject() in /_/src/Moq/Mock`1.cs:line 323
   at Moq.Mock.get_Object() in /_/src/Moq/Mock.cs:line 181
   at Moq.Mock`1.get_Object() in /_/src/Moq/Mock`1.cs:line 281
   at PackagePublisher.ServerAot.Tests.FileOperationServiceTests.Setup() in E:\Project\PackagePublisher\Tests\PackagePublisher.ServerAot.Tests\FileOperationServiceTests.cs:line 38
   at InvokeStub_FileOperationServiceTests.Setup(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
--MissingMethodException
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyInstance(Type proxyType, List`1 proxyArguments, Type classToProxy, Object[] constructorArguments)

-----

One or more child tests had errors
  Exception doesn't have a stacktrace

One or more child tests had errors
  Exception doesn't have a stacktrace

One or more child tests had errors
  Exception doesn't have a stacktrace

**Comment by DotNetNext** [comment]
Mock 是什么东西

**Comment by flier268** [comment]
做單元測試的時候，模擬用的套件，因為我沒有要測試資料庫，所以我模擬ISugarClient

https://github.com/devlooped/moq

**Comment by DotNetNext** [comment]
Can not instantiate proxy of class: SqlSugar.SqlSugarClient.
Could not find a parameterless constructor. (Parameter 'constructorArguments'
sqlsugarclient这个有构造函数，你要包一层没有构造函数的

**Comment by flier268** [comment]
或者把CopyNew改為回傳interface
其他地方像是NavDelete之類的也是一樣問題

**Comment by DotNetNext** [comment]
需提提供一个空DEMO

**Comment by DotNetNext** [comment]
https://www.donet5.com/ask/9/29845

应该是同一个人吗，有疑问在发新Issue

**Comment by flier268** [comment]
不是，這不是我，單純是因為使用NUnit搭配Moq做單元測試是業界常規操作，所以不少人有這個需求

果糖网 ***@***.***> 於 2024年10月15日 週二 下午6:46 寫道：
