### ISSUE TITLE
[BUG] SqlSugar 好像会缓存 datatable , 导致视图更换类型报错

### ISSUE THREAD

**Issue by John0King** [DotNetNext/SqlSugar#1306]
我发现 当视图里面更改字段的类型的时候， sqlsugar 会报错，  而且我确认  SqlSugarClient 每次都是new 的新实例

**Comment by DotNetNext** [comment]
这个数据库缓存不是ORM缓存，一般数据库视图不要用*， 不然需要重新创建视图

**Comment by DotNetNext** [comment]
还有问题吗？

**Comment by John0King** [comment]
> 这个数据库缓存不是ORM缓存，一般数据库视图不要用*， 不然改了表的结构需要重新创建视图

不是视图问题，是Db.ado.GetDataTab()  好像因为语句没改变，缓存了datatable的列类型，然后 我从异常上看，好像是在调用 datareader.getfield 的时候报的错

**Comment by John0King** [comment]
不确定是 ORACLE 底层驱动的问题，还是 SqlSugar的问题

```
System.Exception: TTCExecuteSql:ReceiveExecuteResponse - Unexpected Packet received.
   at OracleInternal.TTC.TTCExecuteSql.ReceiveExecuteResponse(Accessor[]& defineAccessors, Accessor[] bindAccessors, Boolean bHasReturningParams, SQLMetaData& sqlMetaData, SqlStatementType statementType, Int64 noOfRowsFetchedLastTime, Int32 noOfRowsToFetch, Int32& noOfRowsFetched, Int64& queryId, Int32 longFetchSize, Int64 clientInitialLOBFetchSize, Int64 initialLOBFetchSize, Int64 initialJSONFetchSize, Int64[] scnFromExecution, Boolean bAllInputBinds, Int32 arrayBindCount, DataUnmarshaller& dataUnmarshaller, MarshalBindParameterValueHelper& marshalBindParamsHelper, Int64[]& rowsAffectedByArrayBind, Boolean bDefineDone, Boolean& bMoreThanOneRowAffectedByDmlWithRetClause, List`1& implicitRSList, Boolean bLOBArrayFetchRequired)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, Int64 internalInitialJSONFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader()
   at SqlSugar.MyOracleDataAdapter.Fill(DataSet ds)
   at SqlSugar.AdoProvider.GetDataSetAll(String sql, SugarParameter[] parameters)
   at SqlSugar.AdoProvider.<>c__DisplayClass130_0.<GetDataSetAllAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at SqlSugar.AdoProvider.GetDataTableAsync(String sql, SugarParameter[] parameters)
   at CRBPushServer.BackgroundJob.JobBase.CoreUpload(String path, HttpMethod method, String dbView, Action`1 OnBeforeSend, CancellationToken cancellationToken, Action`1 tableOrColumnChange) in F:\众航\HisAndOther\CommonProject\gjcrbjcInterface\CRBPushServer\CRBPushServer\BackgroundJob\JobBase.cs:line 98
   at CRBPushServer.BackgroundJob.Jobs.RealtimeTableJob.Upload_emr_patient_info(CancellationToken cancellationToken) in F:\众航\HisAndOther\CommonProject\gjcrbjcInterface\CRBPushServer\CRBPushServer\BackgroundJob\Jobs\RealtimeTableJob.cs:line 25
   at InvokeStub_TaskAwaiter.GetResult(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by DotNetNext** [comment]
![image](https://github.com/user-attachments/assets/03052191-ce86-4e87-9776-4abdb61183f0)
差不多这样r子， 其他库驱动正常

**Comment by DotNetNext** [comment]
还有疑问发新的issue这个问题ORACLE官方一直没解决

**Comment by John0King** [comment]
@DotNetNext   好的，  您能不能提供一下 这个 issue 连接， 我看看
